#ifndef TRACKINGPLUGIN_GLOBAL_H
#define TRACKINGPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef TRACKINGPLUGIN_LIB
# define TRACKINGPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define TRACKINGPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // TRACKINGPLUGIN_GLOBAL_H
